export const COLORS = {
    lightBaseline: {
        primary: '#089cde',
        onPrimary: '#ffffff',
        primaryContainer: '#B2DFFF',
        onPrimaryContainer: '#0A637F',
        inversePrimary: '#066B9B',
        primaryFixed: '#B2DFFF',
        primaryFixedDim: '#66C5F5',
        onPrimaryFixed: '#0A637F',
        onPrimaryFixedVariant: '#4BAED6',
    },
    lightDynamic31_33: {
        primary: '#31A3FF',
        onPrimary: '#F1F1F1',
        primaryContainer: '#e5f4ff',
        onPrimaryContainer: '#002D3F',
        inversePrimary: '#31A3FF',
        primaryFixed: '#CCE8FF',
        primaryFixedDim: '#98D4FF',
        onPrimaryFixed: '#002D3F',
        onPrimaryFixedVariant: '#99CFF3',
    },
    lightDynamic34Plus: {
        primary: '#46A1FF',
        onPrimary: '#E8F1FF',
        primaryContainer: '#80D6FF',
        onPrimaryContainer: '#003F63',
        inversePrimary: '#41B1FF',
        primaryFixed: '#B3DFFF',
        primaryFixedDim: '#8CCFFF',
        onPrimaryFixed: '#0B6785',
        onPrimaryFixedVariant: '#479CD1',
    },
    darkBaseline: {
        primary: '#089cde',
        onPrimary: '#ffffff',
        primaryContainer: '#0056A3',
        onPrimaryContainer: '#B2DFFF',
        inversePrimary: '#089cde',
        primaryFixed: '#0056A3',
        primaryFixedDim: '#336A8A',
        onPrimaryFixed: '#B2DFFF',
        onPrimaryFixedVariant: '#66C5F5',
    },
    darkDynamic31_33: {
        primary: '#31A3FF',
        onPrimary: '#004F73',
        primaryContainer: '#003F63',
        onPrimaryContainer: '#CCE8FF',
        inversePrimary: '#31A3FF',
        primaryFixed: '#003F63',
        primaryFixedDim: '#004F73',
        onPrimaryFixed: '#CCE8FF',
        onPrimaryFixedVariant: '#66C5F5',
    },
    darkDynamic34Plus: {
        primary: '#46A1FF',
        onPrimary: '#001B29',
        primaryContainer: '#003F63',
        onPrimaryContainer: '#B3DFFF',
        inversePrimary: '#46A1FF',
        primaryFixed: '#003F63',
        primaryFixedDim: '#004F73',
        onPrimaryFixed: '#B3DFFF',
        onPrimaryFixedVariant: '#66C5F5',
    },
    black: "#000000",
    white: "#ffffff",
    success: "#20B958",
    successContainer: "#e9fbf0",
    error: "#F72224",
    errorContainer: "#fee6e7",
    warning: "#EAB308",
    warningContainer: "#fef8e6",
};

